// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGdKvyvgs1ZXUiW05PJUhOwZx64kxFSlU',
    appId: '1:296349278554:web:d086312e4e8d7086a99363',
    messagingSenderId: '296349278554',
    projectId: 'auth-8b5c6',
    authDomain: 'auth-8b5c6.firebaseapp.com',
    storageBucket: 'auth-8b5c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtbJr9xv_KhNzYnpgsv0rOIpj-nHw5SRI',
    appId: '1:296349278554:android:3694e48b6dbffe2ba99363',
    messagingSenderId: '296349278554',
    projectId: 'auth-8b5c6',
    storageBucket: 'auth-8b5c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxvr5jgiYGJ5wOTd1kC7aEQHhX1q4Z20Q',
    appId: '1:296349278554:ios:652098c78bf122cfa99363',
    messagingSenderId: '296349278554',
    projectId: 'auth-8b5c6',
    storageBucket: 'auth-8b5c6.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxvr5jgiYGJ5wOTd1kC7aEQHhX1q4Z20Q',
    appId: '1:296349278554:ios:652098c78bf122cfa99363',
    messagingSenderId: '296349278554',
    projectId: 'auth-8b5c6',
    storageBucket: 'auth-8b5c6.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
